# Generated by ariadne-codegen
# Source: graphql/


from pydantic import Field

from .base_model import BaseModel
from .fragments import CustomerGroupParts, PageInfoParts


class CustomerGroups(BaseModel):
    customer_groups: "CustomerGroupsCustomerGroups" = Field(alias="customerGroups")


class CustomerGroupsCustomerGroups(BaseModel):
    edges: list["CustomerGroupsCustomerGroupsEdges"]
    page_info: "CustomerGroupsCustomerGroupsPageInfo" = Field(alias="pageInfo")


class CustomerGroupsCustomerGroupsEdges(BaseModel):
    node: "CustomerGroupsCustomerGroupsEdgesNode"


class CustomerGroupsCustomerGroupsEdgesNode(CustomerGroupParts):
    pass


class CustomerGroupsCustomerGroupsPageInfo(PageInfoParts):
    pass


CustomerGroups.model_rebuild()
CustomerGroupsCustomerGroups.model_rebuild()
CustomerGroupsCustomerGroupsEdges.model_rebuild()
