# Generated by ariadne-codegen
# Source: graphql/


from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoParts, ThreadParts


class Threads(BaseModel):
    threads: "ThreadsThreads"


class ThreadsThreads(BaseModel):
    edges: list["ThreadsThreadsEdges"]
    page_info: "ThreadsThreadsPageInfo" = Field(alias="pageInfo")


class ThreadsThreadsEdges(BaseModel):
    cursor: str
    node: "ThreadsThreadsEdgesNode"


class ThreadsThreadsEdgesNode(ThreadParts):
    pass


class ThreadsThreadsPageInfo(PageInfoParts):
    pass


Threads.model_rebuild()
ThreadsThreads.model_rebuild()
ThreadsThreadsEdges.model_rebuild()
